server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

pipeline_stages:
  - json:
      expressions:
        log: log
        stream: stream
        time: time
  - labels:
      stream:
  - regex:
      expression: '/var/lib/docker/containers/(?P<container_id>[0-9a-f]{64})/'
      source: filename
  - labels:
      container_id:
  - output:
      source: log